### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by toolswatch** [UShan89/vFeed-UI#2]
Hi man,

I think you need some documentation with the vFeed UI.  Can you create a wiki with install requirements and quick how to ?

Thanks so much

@toolswatch

**Comment by UShan89** [comment]
Sure thing,

The first thing I would do is create a step-by-step instruction through
wiki.Thank you for the tip.

Regards
Uday

**Comment by UShan89** [comment]
@toolswatch I am sorry for this delay in documentation. I now have instructions ready for installation and getting started.
